service: web-api

provider:
  name: aws
  region: us-east-2
  runtime: python3.6
  memorySize: 128
  timeout: 10

  deploymentBucket:
    name: good-emporium-artifacts
    serverSideEncryption: KMS

  environment:
    ENVIRONMENT: p
    REGION: "us-east-2"
    TABLE_ORGANIZATIONS: ${opt:stage, self:provider.stage}-organizations

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-2:*:table/*"

package:
  include:
    - functions/*.py

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  list:
    handler: functions/organizations_handler.ls
    events:
      - http:
          path: organizations
          method: get
          cors:
            origins:
            - '*'

  create:
    handler: functions/organizations_handler.create
    events:
      - http:
          path: organizations
          method: post
          cors:
            origins:
            - '*'

  retrieve:
    handler: functions/organizations_handler.retrieve
    events:
      - http:
          path: organizations/{id}
          method: get
          cors:
            origins:
            - '*'

  update:
    handler: functions/organizations_handler.update
    events:
      - http:
          path: organizations/{id}
          method: put
          cors:
            origins:
            - '*'

  delete:
    handler: functions/organizations_handler.delete
    events:
      - http:
          path: organizations/{id}
          method: delete
          cors:
            origins:
            - '*'

resources:
  Resources:
    OrganizationsTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.TABLE_ORGANIZATIONS}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
