version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6-stretch-node

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - .

attach_workspace: &attach_workspace
  attach_workspace:
    at: .

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install the Python dependencies
          command: sudo pip install -r requirements.dev.txt
      - *persist_to_workspace

  deploy_dev_testing_circle_remove_me:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Install Serverless
          command: npm install -g
      - run:
          name: Deploy to the dev environment (just testing circle here)
          command: serverless deploy --stage v0-dev

  deploy_staging:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Install Serverless
          command: npm install -g
      - run:
          name: Deploy to the staging environment
          command: serverless deploy --stage v0-dev

  deploy_prod:
    <<: *defaults
    steps:
      - *attach_workspace
      - run:
          name: Install Serverless
          command: npm install -g
      - run:
          name: Deploy to the prod environment
          command: serverless deploy --stage v0

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - deploy_dev_testing_circle_remove_me:
          requires:
            - build
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/

      - deploy_staging:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /^v.*/

      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
